[workspace]
authors = ["Micha≈Ç Olejnik <maricpl@wp.pl>"]
channels = ["conda-forge"]
name = "automatic_tablature_extraction"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
ipykernel = "*"
numpy = "1.22.4"
librosa = "*"
ruff = ">=0.6.2,<0.7"
matplotlib = ">=3.5.3,<4"
pandas = "*"


[pypi-dependencies]
openunmix = "*"
soundfile = "*"
basic-pitch = "*"
pretty_midi = ">=0.2.8"
bokeh = "==2.4.0"
visual_midi = "*"
yt-dlp =  { version = "*", extras = ["default"]}
tayuya = "*"
